# Generated by Django 3.2.6 on 2021-08-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BsaleAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url_image', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
    ]
