# Generated by Django 3.2.6 on 2021-08-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BsaleAPI', '0002_auto_20210808_2057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
